"""initial schema: 11 tablo

Revision ID: 41dbbfae3279
Revises: 
Create Date: 2026-08-05 20:34:16.080450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41dbbfae3279'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('rolling_courses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('min_orders', sa.Integer(), nullable=True),
    sa.Column('max_orders', sa.Integer(), nullable=True),
    sa.Column('first_main_group_placed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('current_length_mm', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('reverse_width_events_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('order_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'active', 'completed', 'failed')", name='ck_rolling_courses_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_number')
    )
    op.create_table('slab_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_ref', sa.String(length=50), nullable=True),
    sa.Column('steel_grade', sa.String(length=50), nullable=True),
    sa.Column('width_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('hardness', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heating_temp_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('slab_width_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('slab_thickness_mm', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('slab_length_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('theoretical_rolling_length', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('order_class', sa.String(length=20), nullable=False),
    sa.Column('main_group_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("order_class IN ('main', 'transition')", name='ck_slab_orders_order_class'),
    sa.CheckConstraint("source IN ('synthetic', 'manual')", name='ck_slab_orders_source'),
    sa.CheckConstraint("status IN ('pending', 'reserved', 'scheduled', 'in_progress', 'completed', 'skipped')", name='ck_slab_orders_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slab_orders_main_group_id', 'slab_orders', ['main_group_id'], unique=False)
    op.create_index('ix_slab_orders_order_class_status', 'slab_orders', ['order_class', 'status'], unique=False)
    op.create_index('ix_slab_orders_status', 'slab_orders', ['status'], unique=False)
    op.create_table('training_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_slots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('slab_order_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('hardness', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heating_temp_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cumulative_length_mm', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('is_reverse_width', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('main', 'transition')", name='ck_course_slots_role'),
    sa.ForeignKeyConstraint(['course_id'], ['rolling_courses.id'], ),
    sa.ForeignKeyConstraint(['slab_order_id'], ['slab_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'position_index', name='uq_course_slots_course_position')
    )
    op.create_index('ix_course_slots_course_position', 'course_slots', ['course_id', 'position_index'], unique=False)
    op.create_table('live_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('order_generated', 'course_started', 'main_group_selected', 'transition_selected', 'slab_placed', 'course_completed', 'course_failed', 'constraint_violation', 'simulation_started', 'simulation_paused', 'simulation_resumed', 'simulation_stopped', 'manual_step')", name='ck_live_events_event_type'),
    sa.ForeignKeyConstraint(['course_id'], ['rolling_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_events_created_at', 'live_events', ['created_at'], unique=False)
    op.create_table('main_product_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('steel_grade', sa.String(length=50), nullable=True),
    sa.Column('first_order_id', sa.BigInteger(), nullable=True),
    sa.Column('last_order_id', sa.BigInteger(), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('initial_group_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='available', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'scheduled', 'partially_used')", name='ck_main_product_groups_status'),
    sa.ForeignKeyConstraint(['first_order_id'], ['slab_orders.id'], ),
    sa.ForeignKeyConstraint(['last_order_id'], ['slab_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # slab_orders.main_group_id -> main_product_groups.id: cember bagimliligi (main_product_groups da
    # slab_orders'a first/last_order_id ile FK veriyor). Bu yuzden bu FK, her iki tablo da var oldugunda
    # ayri bir ALTER TABLE adiminda ekleniyor (bkz. TASARIM.md SS12.1 Faz 1 notu).
    op.create_foreign_key(
        'fk_slab_orders_main_group_id',
        'slab_orders', 'main_product_groups',
        ['main_group_id'], ['id'],
    )
    op.create_table('model_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('checkpoint_path', sa.Text(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_run_id', sa.BigInteger(), nullable=True),
    sa.Column('hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('manager', 'worker')", name='ck_model_versions_level'),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager_decisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_mask', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_group_id', sa.BigInteger(), nullable=True),
    sa.Column('reward', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('model_version_id', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['rolling_courses.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['selected_group_id'], ['main_product_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tick_interval_ms', sa.Integer(), nullable=True),
    sa.Column('manager_model_version_id', sa.BigInteger(), nullable=True),
    sa.Column('worker_model_version_id', sa.BigInteger(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mode IN ('autonomous', 'manual', 'hybrid')", name='ck_simulation_runs_mode'),
    sa.CheckConstraint("status IN ('running', 'paused', 'stopped')", name='ck_simulation_runs_status'),
    sa.ForeignKeyConstraint(['manager_model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['worker_model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_decisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('manager_decision_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_mask', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_transition_order_id', sa.BigInteger(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('reward', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('model_version_id', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['rolling_courses.id'], ),
    sa.ForeignKeyConstraint(['manager_decision_id'], ['manager_decisions.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['selected_transition_order_id'], ['slab_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- TASARIM.md SS3.12: view v_active_course_state ---
    op.execute(
        """
        CREATE VIEW v_active_course_state AS
        SELECT rc.id AS course_id, rc.course_number, rc.status, rc.order_count,
               rc.current_length_mm, rc.reverse_width_events_count,
               cs.position_index, cs.role, cs.width_mm, cs.thickness_mm,
               cs.hardness, cs.heating_temp_c, cs.is_reverse_width, cs.slab_order_id
        FROM rolling_courses rc
        LEFT JOIN course_slots cs ON cs.course_id = rc.id
        WHERE rc.status = 'active'
        ORDER BY cs.position_index
        """
    )

    # --- TASARIM.md SS3.11: constraint_config varsayilan deger seed'i ---
    # NOT: Referans makale (Wang, Sun, Gu & Chen 2026) bu esiklerin sayisal degerlerini
    # paylasmiyor -- makaledeki egitim/test verisi ticari gizli oldugu icin (bkz. TASARIM.md SS0.2).
    # Asagidaki degerler muhendislik tahminine dayali YER TUTUCU (placeholder) degerlerdir;
    # Faz 2/3'te sentetik veri istatistiklerine gore kalibre edilecektir (bkz. TASARIM.md SS13).
    constraint_config_table = sa.table(
        "constraint_config",
        sa.column("key", sa.String),
        sa.column("value", sa.Numeric),
        sa.column("description", sa.Text),
    )
    op.bulk_insert(
        constraint_config_table,
        [
            {
                "key": "delta_w",
                "value": 50,
                "description": "Ardisik orderlar arasi maksimum izin verilen genislik sicramasi (mm) - Delta w, es. 17. YER TUTUCU.",
            },
            {
                "key": "delta_t",
                "value": 0.5,
                "description": "Ardisik orderlar arasi maksimum izin verilen kalinlik sicramasi (mm) - Delta t, es. 18. YER TUTUCU.",
            },
            {
                "key": "delta_h",
                "value": 5,
                "description": "Ardisik orderlar arasi maksimum izin verilen sertlik sicramasi - Delta h, es. 19. YER TUTUCU.",
            },
            {
                "key": "delta_theta",
                "value": 30,
                "description": "Ardisik orderlar arasi maksimum izin verilen isitma sicakligi sicramasi (C) - Delta theta, es. 20. YER TUTUCU.",
            },
            {
                "key": "Kz",
                "value": 50000,
                "description": "Ters genislik (reverse width) bolgesi esigi: kumulatif haddeleme uzunlugu (mm) - Kz, es. 23. YER TUTUCU.",
            },
            {
                "key": "Lr",
                "value": 3,
                "description": "Kz bolgesi icinde izin verilen maksimum ters genislik olay sayisi - Lr, es. 24. YER TUTUCU.",
            },
            {
                "key": "m_min",
                "value": 60,
                "description": "Bir haddeleme kursundaki minimum izin verilen order sayisi - m_min, es. 11. YER TUTUCU (makale SS2.2.2: 'kurs tipik olarak 60-100 order icerir').",
            },
            {
                "key": "m_max",
                "value": 100,
                "description": "Bir haddeleme kursundaki maksimum izin verilen order sayisi - m_max, es. 11. YER TUTUCU (makale SS2.2.2: 'kurs tipik olarak 60-100 order icerir').",
            },
            {
                "key": "soft_transition_limit",
                "value": 3,
                "description": "Worker odul fonksiyonunda ek ceza (beta_2) uygulanmaya baslanan gecis slabi sayisi esigi - G, es. 35. Makalede acikca belirtiliyor: 'the vast majority of feasible transitions can be achieved with at most three transition orders'.",
            },
        ],
    )


def downgrade() -> None:
    # view, kendisinin bagli oldugu rolling_courses/course_slots tablolarindan once dusurulmeli
    op.execute("DROP VIEW IF EXISTS v_active_course_state")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_decisions')
    op.drop_table('simulation_runs')
    op.drop_table('manager_decisions')
    op.drop_table('model_versions')
    # cember FK'yi, main_product_groups dusurulmeden once kaldirmak gerekiyor
    op.drop_constraint('fk_slab_orders_main_group_id', 'slab_orders', type_='foreignkey')
    op.drop_table('main_product_groups')
    op.drop_index('ix_live_events_created_at', table_name='live_events')
    op.drop_table('live_events')
    op.drop_index('ix_course_slots_course_position', table_name='course_slots')
    op.drop_table('course_slots')
    op.drop_table('training_runs')
    op.drop_index('ix_slab_orders_status', table_name='slab_orders')
    op.drop_index('ix_slab_orders_order_class_status', table_name='slab_orders')
    op.drop_index('ix_slab_orders_main_group_id', table_name='slab_orders')
    op.drop_table('slab_orders')
    op.drop_table('rolling_courses')
    op.drop_table('constraint_config')
    # ### end Alembic commands ###
